# Generated by Django 4.0.5 on 2022-07-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_changerequest_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrequest',
            name='port',
            field=models.PositiveIntegerField(default=0, verbose_name='Port'),
        ),
    ]
